### ISSUE TITLE
Add "Setting Changed" popup whenever a changed setting is saved.

### ISSUE THREAD

**Issue by codencoding** [codencoding/web-startpage-v2#30]
Have it appear above the #main_display elem with 1/3 of its width.

Transition should translate up from the main display element and then translate back down after a short time.

**Comment by renzocarara** [comment]
Hi Chase,
I would like to try this.

I'm not sure I correctly undesrstood your indications.
case1.
you want to animate the popup make it entering from the top side,
stopping a while in the middle of the display,
and then exiting from the bottom side.

case2.
you want the popup appears in the middle of the display,
fading in, and then after a while, disappearing fading out 

Let me know which one you intended.

Ciao.
r

**Comment by renzocarara** [comment]
case1.  https://drive.google.com/file/d/1jOdffkn23olOUCL2s92f53HBVrUvAkvw/view?usp=sharing
case2.  https://drive.google.com/file/d/1R9V6EUUgNlCDe7d_gCeKmoBprJzWgJ1g/view?usp=sharing

**Comment by codencoding** [comment]
I'd say the idea I had in mind is closest to your case 1 situation. Instead of the image going from the top of the entire screen, pausing in the middle, and then exiting out from the bottom, it should originate from _behind_ the square window in the center identified as #main_display. It'd then move up into the position shown in this image, pause for 1-2s, then descend back down behind the #main_display.

I think this is better than having the notification appear in the middle of all the settings since it doesn't obscure any of the settings when something is changed.

![setting_changed_idea](https://user-images.githubusercontent.com/36287664/98450877-61834000-20f5-11eb-80ad-c913d1fc6928.png)

**Comment by renzocarara** [comment]
Hi Chase,
I think I got you. It shouldn't be too difficult to make it.
But there's another issue:
now I'm using my laptop, a 14" screen, and as you can see in the screenshot below, the room to arrange the popup seems not enough! There's a very tiny space up the main square window.
Generally I use a 19" desktop screen, and on that display, spaces are like the snapshot you attached above.
So, what do you think?
<img width="960" alt="screenshot" src="https://user-images.githubusercontent.com/54705288/98451165-8bfbea00-2143-11eb-824a-9ff567c937d9.png">

**Comment by codencoding** [comment]
Ah I see the dilemma here. To account for responsiveness, I think it'd be a good idea to have both ideas implemented. Use your case 1 idea for a center-positioned notification whenever the window's height isn't enough to allow for my idea. If there is enough space, then use the error notification above the main display. 

Should be doable using @media to check window height. The #main_display is set to max out at 500pixels or 97% of the view height, so whenever @media has height of 500px + 8px for bottom margin + 35px for notification height + 8px for top margin, switch the styling to do the above #main_display transition instead. A bit complicated but I think it gets the best of both worlds and stays responsive.

**Comment by renzocarara** [comment]
Chase,
I'm looking at the style file.
I think there are some problems.

`#main_display {
    background-color: var(--primary_color);
    /* background-image: url("imgs/center_images/1602608434583.jpg"); */
    width: 97vw;                     <----------- these 2 lines I think don't work if you use max-width and max-height properties below
    height: 97vw;                    <----------- the actual size of the square window is 550px x 550px
    min-width: 370px;
    min-height: 370px;
    max-width: 550px;                <-------------- these 2 lines are effective, the actual size of the window square is 550px x 550px
    max-height: 550px;               <--------------
    position: absolute;
    top: 50%;
    left: 50%;
    -ms-transform: translate(-50%, -50%);
    transform: translate(-50%, -50%);
    /* border: 1px var(--tertiary_color) inset; */
    box-shadow:  6px 6px 4px #000000;
    z-index: 0;
}

@media ((max-width: 500px) or (max-height: 500px)) {  <--- here there's a syntax error,  my VSC is saying "identifier expected.."
    #main_display {                                                          <--- please check your editor if give you an error/warning  
        max-width: 97vh;
        max-height: 97vh;
    }
}`

I guess your itention was to set the square window size to 97% of the available viewport space when the device screen is
less then 550px (?)
I found the following syntax:
@media screen and (max-width: 550px), (max-height: 550px) {
....
it should work as follow: when you are on a device with width<=550px OR a device with height<=550px then
set the max width and max height of the square window to 97% of device view **height**.

Tomorrow, I will continue to work to this.

**Comment by codencoding** [comment]
The current solution for the error notifications looks solid and is nicely implemented in your latest pull request. For future responsive design, I'll make a new issue (#40) to start dealing with the responsiveness of the site and we can discuss how to proceed with the site's design given different window sizes.
