### ISSUE TITLE
Add calendar widget to 3rd tab.

### ISSUE THREAD

**Issue by codencoding** [codencoding/web-startpage-v2#4]

**Comment by Denpex** [comment]
I would like to this task, but first is it okay if I integrate the calendar from this [npm package](https://www.npmjs.com/package/flatpickr) ? And also can you provide more detail on how the calendar should look and behave ?

**Comment by codencoding** [comment]
> 
> 
> I would like to do this task, but first is it okay if I integrate the calendar from this [npm package](https://www.npmjs.com/package/flatpickr) ? And also can you provide more detail on how the calendar should look and behave ?

As cool as the flatpickr package looks, I intended for this widget to be a google calendar widget so the user can link up to their gmail account and sync events that way, easily sourced directly from google calendar's api.

What utility do you think would come from implementing a flatpickr calendar over a google calendar? I think hooking up flatpickr calendar to google calendar's API and populating it through the site will end up being more trouble than it's worth.

**Comment by Denpex** [comment]
@codencoding , it was my mistake for not looking at the source code, beforehand I saw that a google calendar is already implemented. If there are any other tasks available I would like to have a go at them.

**Comment by codencoding** [comment]
> 
> 
> @codencoding , it was my mistake for not looking at the source code beforehand, I see that a google calendar is already implemented. If there are any other tasks available I would like to have a go at them.

If you'd like to make suggestions for new features feel free to create a new issue for it. I didn't expect anyone besides me to work on this project so please let me know if you think the site is missing or could use a new idea.

Otherwise, the other open features left to implement right now are the [Spotify now playing plugin](https://github.com/codencoding/web-startpage-v2/issues/5) and a [left-to-right gradient coloring](https://github.com/codencoding/web-startpage-v2/issues/1) for the main window border. I'll be bugfixing and adjusting responsiveness for the site for some time so do feel free to work on those if you like.

**Comment by Denpex** [comment]
@codencoding assign me to #5 i want to do it.

**Comment by codencoding** [comment]
> 
> 
> @codencoding assign me to #5 i want to do it.

As much as I'd like to, I can't do that until you've created a comment in the existing issue.
